# ============================================
# API Gateway Yapılandırması
# ============================================

server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # Redis yapılandırması (Rate Limiting için)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

